export const GET_PLAYER_SUCCESS = 'GET_PLAYER_SUCCESS';
export const ADD_PLAYER_SUCCESS = 'ADD_PLAYER';

export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS';
export const ADD_SQUARES_TO_HISTORY = 'ADD_SQUARES_TO_HISTORY';